package dev.cniekirk.wikidroid.core.seedmap

/**
 * Every biome id the pinned cubiomes can return for any [McVersion], with the name it gives the biome in
 * the newest version that has it. Ids are stable across versions; only some names changed (id 3 was
 * `mountains`, now `windswept_hills`), and the newest name is what the wiki uses.
 *
 * Generated from a host build of the pinned commit (`biomeExists` and `biome2str` for ids 0-255 in every
 * version); `BiomeCatalogNativeTest` re-derives it from the real library, so a cubiomes update that adds
 * or renames a biome fails there until this table is regenerated.
 */
object BiomeCatalog {
    val names: Map<Int, String> =
        mapOf(
            0 to "ocean",
            1 to "plains",
            2 to "desert",
            3 to "windswept_hills",
            4 to "forest",
            5 to "taiga",
            6 to "swamp",
            7 to "river",
            8 to "nether_wastes",
            9 to "the_end",
            10 to "frozen_ocean",
            11 to "frozen_river",
            12 to "snowy_plains",
            13 to "snowy_mountains",
            14 to "mushroom_fields",
            15 to "mushroom_field_shore",
            16 to "beach",
            17 to "desert_hills",
            18 to "wooded_hills",
            19 to "taiga_hills",
            20 to "mountain_edge",
            21 to "jungle",
            22 to "jungle_hills",
            23 to "sparse_jungle",
            24 to "deep_ocean",
            25 to "stony_shore",
            26 to "snowy_beach",
            27 to "birch_forest",
            28 to "birch_forest_hills",
            29 to "dark_forest",
            30 to "snowy_taiga",
            31 to "snowy_taiga_hills",
            32 to "old_growth_pine_taiga",
            33 to "giant_tree_taiga_hills",
            34 to "windswept_forest",
            35 to "savanna",
            36 to "savanna_plateau",
            37 to "badlands",
            38 to "wooded_badlands",
            39 to "badlands_plateau",
            40 to "small_end_islands",
            41 to "end_midlands",
            42 to "end_highlands",
            43 to "end_barrens",
            44 to "warm_ocean",
            45 to "lukewarm_ocean",
            46 to "cold_ocean",
            47 to "deep_warm_ocean",
            48 to "deep_lukewarm_ocean",
            49 to "deep_cold_ocean",
            50 to "deep_frozen_ocean",
            51 to "seasonal_forest",
            52 to "rainforest",
            53 to "shrubland",
            127 to "the_void",
            129 to "sunflower_plains",
            130 to "desert_lakes",
            131 to "windswept_gravelly_hills",
            132 to "flower_forest",
            133 to "taiga_mountains",
            134 to "swamp_hills",
            140 to "ice_spikes",
            149 to "modified_jungle",
            151 to "modified_jungle_edge",
            155 to "old_growth_birch_forest",
            156 to "tall_birch_hills",
            157 to "dark_forest_hills",
            158 to "snowy_taiga_mountains",
            160 to "old_growth_spruce_taiga",
            161 to "giant_spruce_taiga_hills",
            162 to "modified_gravelly_mountains",
            163 to "windswept_savanna",
            164 to "shattered_savanna_plateau",
            165 to "eroded_badlands",
            166 to "modified_wooded_badlands_plateau",
            167 to "modified_badlands_plateau",
            168 to "bamboo_jungle",
            169 to "bamboo_jungle_hills",
            170 to "soul_sand_valley",
            171 to "crimson_forest",
            172 to "warped_forest",
            173 to "basalt_deltas",
            174 to "dripstone_caves",
            175 to "lush_caves",
            177 to "meadow",
            178 to "grove",
            179 to "snowy_slopes",
            180 to "jagged_peaks",
            181 to "frozen_peaks",
            182 to "stony_peaks",
            183 to "deep_dark",
            184 to "mangrove_swamp",
            185 to "cherry_grove",
            186 to "pale_garden",
            187 to "sulfur_caves",
            188 to "dappled_forest",
        )
}
